# coding: utf-8
TruePositive=[
"porausten tarkoitus on selvittää muun muassa kuinka laaja esiintymä todellisuudessa on ja missä määrin sitä voitaisiin kestävästi hyödyntää.",
"jos suinkin aikaa on pitkän matkan päätteeksi juodaan yhteiset kahvit keittiön pöydän ääressä.",
"naulakon tulee kestää vaatteiden paino tuolin on oltava tukeva ja kenkien pysyttävä kenkätelineessä.",
"lokki kirkuu ryöstää nakkisämpylän jopa kädestä ja sotkee ulosteellaan paikkoja.",
"työelämässä odotetaan nykyään sosiaalisuutta ja kykyä esiintyä tai ainakin tarvittaessa pitää uskaltaa avata suunsa kokouksissa.",
"taikuri oli saavuttanut valta aseman yhteisössä ja sai hiljaisen hyväksynnän niljakkaalle toiminnalleen.",
"siellä muisteltiin hymyssä suin tapausta kun lääkäri ei osannutkaan pukea vanhukselle tukisukkia takaisin jalkaan.",
"suurimman osan ihmiskunnan historiasta henkilökohtainen valinnanvara on ollut rajattua.",
"viime viikkoina väkivaltaiseksi muuttuneet mielenosoitukset vaikuttivat lauantaina päivällä rauhoittuneen.",
"tuoreen kyselyn mukaan ammattikouluissa tyttöjen keskuudessa nuuskaaminen on yleistynyt paikoin jopa räjähdysmäisesti.",
"tekijät saivat uhrin kertomaan pankkikorttinsa tunnusluvun sekä pankkitilinsä käyttäjätunnuksen ja salasanan.",
"rajuja ukonilmoja on alkuviikosta tehdyn ennusteen mukaan luvassa keskiviikoksi kaakossa sijaitseviin maakuntiin.",
"se on oikeasti puusta muotoiltu kynttilänjalka mutta nimensä esine on saanut herkkupalaa muistuttavasta muodosta.",
"pelastusjoukot ovat etsineet kateissa olleita ihmisiä myrskyn aiheuttaman maanvyöryn alta.",
"syyttäjä vaatii vähintään vuoden ehdotonta vankeusrangaistusta rahtialuksen kapteenille törkeästä veropetoksesta.",
"poliisi otti useita henkilöitä kiinni näyttävässä kotietsinnässä jossa rynnäköitiin panssaroidulla ajoneuvolla suoraan olohuoneeseen.",
"moni jättää aamupalan syömättä esimerkiksi kiireen nälän puutteen tai oksettavan olon vuoksi.",
"vanha junakalusto aiheuttaa niin voimakasta maaperän tärinää että lähialueen kiinteistöjen seinät halkeilevat.",
"työntekijämme saavat vähintään samat edut kuin muissakin alan yrityksissä mutta ilman hierarkiaa ja byrokratiaa.",
"hovioikeudessa valelääkärin tempauksista kunnalle aiheutuneet taloudelliset vahingot arvioitiin odotettua pienemmiksi.",
"uusissa tiloissa iloa ja valoa silmälle tuovat lasiseinät hempeät värit isot eläinvalokuvat ja hauskat piirroshahmot.",
"turvallisuuden lisäksi pitäisi ottaa huomioon muun muassa liikenteen sujuvuus ympäristö ja paikallisten tottumukset.",
"meiltä ei löydy valmiita paketteja vaan ratkaisut räätälöidään aina yhdessä asiakkaan kanssa ja heidän tarpeeseensa.",
"viljelijät ovat yhä toiveikkaita sillä kasvustot ovat pysyneet pystyssä ja pellot ovat toistaiseksi kantavia.",
"laite voi tulevaisuudessa olla hyödyksi myös lievissä turvallisuustilanteissa ja rikosten selvityksessä.",
"politiikan ei pidä olla haudanvakavaa mutta vitsailun ei myöskään pidä olla itsetarkoitus.",
"kaikki toimintamme perustuu siihen että jokaisella on vapaus ja vastuu toimia parhaaksi katsomallaan tavalla omalla vastuualueellaan.",
"jos on ujo eikä osaa ilmaista itseään sanoin kenties sen pystyy tekemään luontevammin kasvattamalla parran.",
"arjen tavat muodostuvat toistamalla ja toistojen kautta asioista tulee luontevaa kenelle hyvänsä.",
"kummallakaan ehdokkaalla ei ole aiempaa poliittista kokemusta ja he ovatkin keränneet kannatusta eliitistä riippumattomina uudistajina.",
"ihmisten kohtaamisen ohessa papilla oli aikaa tutkia hautausmaata hautoja ja niihin liittyviä elämäntarinoita.",
"neljän auton kolari aiheutti aamulla valtavan liikenneruuhkan kehätiellä.",
"tavoitteena on luoda kokonaisuus jolla tehdään vaikuttavaa ennaltaehkäisevää työtä eri puolilla maata.",
"keskiverto kotitalouteen toimitetaan nykyisin keskimäärin viisi mutta pian enää kolme kirjettä viikossa.",
"lain mukaan suojatien pitäisi olla turvallinen paikka mutta se velvoittaa myös jalankulkijaa.",
"helppohoitoiset huonekasvit ovat usein varma valinta mutta niidenkin hoidossa voi mennä vaikka mitä pieleen.",
"muinainen kolikkokätkö on tutkimuksissa paljastanut ettei veronkierto suinkaan ole vain tämän päivän rikos.",
"vankilasta saadut tiedot ovat herättäneet epäilyjä että valvonta ei ollut riittävän tarkkaa.",
"teknologia vaikuttaa tulevaisuudessa tarvittavien taitojen lisäksi opetuksen ja oppimisen tapoihin.",
"toimitamme sitten tiimejä ratkaisuja tai yksittäisiä kehittäjiä on asiakkaan käytössä aina koko yrityksen laaja osaaminen ja oikeanlainen asenne.",
"kyseessä on yksi alueen vanhimmista kantatiloista josta varhaisimmat merkinnät ajoittuvat satojen vuosien taakse.",
"ilmastonmuutos voi tehdä vakuuttamisen mahdottomaksi pahimmilla riskivyöhykkeillä.",
"löytöjen joukossa on paljon keramiikkaa ja kolikoita mutta myös muun muassa satoja kenkiä ja useita amuletteja.",
"yöllisessä yhteenotossa viranomaiset ottivat kiinni useita salakalastajia ja takavarikoivat näiden kumiveneet ja päähineet.",
"aiheesta tietämättömälle sukukypsä ankerias saattaa olla hämmästyttävä jopa pelottava näky.",
"opiskelijat ovat ainoa ihmisryhmä jonka oletetaan elävän velaksi ja käyvän vielä töissä lomalla.",
"lavojen parketeilla on käyty pyörähtelemässä entistä laajemmalta alueelta ja tanssijoiden joukossa on ollut aiempaa enemmän nuorempaa polvea.",
"vintin eristämisestä ei olisi tullut mitään koska vanhat tavarat olisivat jääneet sinne purujen alle.",
"elostelevasta elämänkerrasta tulee rehentelyn sivumaku ja se saa sapen kiehumaan.",
"yhtiön velkojilla on ollut tähän perjantaihin asti aikaa ilmoittaa saatavansa viranomaisille."]
